language: node_js
node_js: node
services:
  - mongodb
cache:
  directories:
    - node_modules
env:
  - CI=true
deploy:
  provider: heroku
  api_key:
    secure: HKEOpQH9eHx0JXWSi8QZnltCosuFOOsdA8zkqESjTAw1/8uPsshqYGibe6+JT8s8z8odLOpVHR87+9XZZS4JWPFfAElGhyQvbyZdUxMZWAVbzLCPqH+oW7nv0cgHzhJk62MPpisHNq9xdTGnM1EdQ6D6/2Q5mH03ypw9eM/aN31oKcm4KVf3lgLHtZY1Etud75EkLJrIP25MRxUibhC3LKgcmUmfPFaBBub2YmtLIrqgn5/S4ojnF6bycK5X4ZWzRgH8GK3+ToTvvQZB5CsK1w5RcOU+jDI+JsZzyWF0s1K99yD5sFzALuIXHqv3FMm04UPSsIV+YodjdR5UVJeelE/cu+RrPARORAOELo9s7EA4J1+HRhN2i65gbXCsY6HWAtS6B5UG6rZVHzb2ESQzRP9xUh6Doqx0aI21HIv53R+pFmXVqAX/PAM79BCixAI+xUam2WSd8UunfMRXIf46HJ/r9RjUZ5bGCB9THi7O/Nx8F3hnvMkWowWroxGA2qTMbdQG60AJjxLli8tEhXQiMQ7V6AcjVFvAHxY2iuhDzyFIYTGgUWNeG/K8F3KlyMw71bHulpIZflQ7L60ti5Iw3L4NSSmLQV2VnB88KO8xzCPvMufDKiTclGZu29hNgf+hS4o324femMvb0gBYPnmWhHmvTY3TEwfZ6+fGnAoPaa8=
  app: lit-dusk-99415
  on:
    repo: AlexMcComb/peek
