language: node_js
node_js: node
cache:
  directories:
    - node_modules
env:
  - CI=true
deploy:
  provider: heroku
  api_key:
    secure: oO6yRN8hNPve2bT+CpaXTinj7J0j6rtU4aZYtSpobg/2VrrglDMD6YOqTHe0OF5selBuQFwyOwqHADFbJqninB4g0mcWE+F1JzY3ajNjLEJkr0oqmBDDKL2a387gHvg09u74lLfi+fIR+Ts4CTmXBQMbCZOSpTXkcZ/W5f4E6sgE7rptu9H/bCdOVo+2f8U19LNs1M8SgzzR9mClMe80vrGMci+T6vLu7jCwM0/vmlBGMQrqZNPokpuprL4Ds2yivCWb8NgEI/AOxOAuKr+4jxXvOBBLqT1CiYY0icZ+6VeduoV7KNKpB7UjcJ+7ovTcjQpfmiRI9HsLqqkjxmJai4JY1v2pepeCXAJb0X+OYfHeOB2/o2WPHe31j5QU/2sx0y+FF+l92WVIUewP5k2YaIQM8o8GsRp0o6j+g1/rLY5xt2zD8N2DEjUPnDoLYjrSjbCwhogYEDyzekE7XNCDA3ss6rj4Au59gnu4Wcow0Hc4HlrAkqTtCE4Al5G0HLlC7wJ2Buzd2ICdSjZok27NrQp3ouXf5F06zpQCoVySelr2K3vGYxOvycp/V6lQJwZ1hEr8M4eVygGDVReHMDa2RnMNSChpT4BNrSbzGBFN2LOE+//2K30Xl2HW+cKpkuzAA0GpcYaIYnqJuWsQY38a2zimBrE9lk+9NgI75ppSuzQ=
  app: peaceful-castle-44452
  on:
    repo: AlexMcComb/peek
